name = 'craftcoinmeme'
main = "main.py"
compatibility_date = "2024-05-10"
compatibility_flags = ["python_workers"]

[env.production.vars]
GITHUB_OWNER = "and1-lol"
GITHUB_REPO = "CRCMeme"

[observability.logs]
enabled = true
invocation_logs = true
